# ==========================================
# Bella Bride Wedding Salon
# Helm values.yaml
# ==========================================

# Number of application Pods
replicaCount: 3


# ==========================================
# Docker Image - AWS ECR
# ==========================================

image:
  repository: 107014414047.dkr.ecr.us-east-1.amazonaws.com/bella-bride-wedding-salon
  tag: "latest"
  pullPolicy: Always


# ==========================================
# Kubernetes Service
# ==========================================

service:
  type: ClusterIP
  port: 80
  targetPort: 80


# ==========================================
# CPU and Memory
# ==========================================

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"

  limits:
    cpu: "500m"
    memory: "512Mi"


# ==========================================
# Readiness Probe
# ==========================================

readinessProbe:
  path: /
  port: 80
  initialDelaySeconds: 5
  periodSeconds: 10


# ==========================================
# Liveness Probe
# ==========================================

livenessProbe:
  path: /
  port: 80
  initialDelaySeconds: 15
  periodSeconds: 20


# ==========================================
# Rolling Update Strategy
# ==========================================

strategy:
  type: RollingUpdate
  maxUnavailable: 0
  maxSurge: 1
