# values.yaml
# Bella Bride Wedding Salon

replicaCount: 3

image:
  repository: 107014414047.dkr.ecr.us-east-1.amazonaws.com/bella-bride-wedding-salon
  pullPolicy: IfNotPresent
  tag: "v1"

imagePullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: bella-bride.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

livenessProbe:
  enabled: true
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 15
  periodSeconds: 20

readinessProbe:
  enabled: true
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70

podDisruptionBudget:
  enabled: true
  minAvailable: 1

strategy:
  type: RollingUpdate
  rollingUpdate:
    maxUnavailable: 0
    maxSurge: 1

nodeSelector: {}

tolerations: []

affinity: {}
