apiVersion: v1
kind: Service

metadata:
  name: bella-bride
  labels:
    app: bella-bride

spec:
  type: {{ .Values.service.type }}

  selector:
    app: bella-bride

  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
